stages:
  - build
  - test

before_script:
  - apk update
  - apk upgrade
  - apk add --no-cache cmake build-base

build:
  stage: build
  image: alpine
  script:
    - mkdir build
    - cd build
    - cmake ../TP-Refacto/
    - cmake --build .
  artifacts:
    paths:
      - build

test:
  stage: test
  image: alpine
  script:
    - cd build
    - UnitTests/Unit-Tests
  dependencies:
    - build

