build:
  stage: build
  tags:
    - linux
  image: gcc
  before_script:
    - apt-get update - apt-get install --yes cmake
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
      - build

test:
  stage: test
  script:
    - cd build
    - UnitTests/Unit-Tests
