stages:
  - build
  - test

build:
  stage: build
  image: ubuntu:latest
  script:
    - apt-get update -qq
    - apt-get install -y qtbase5-dev cmake build-essential
    - mkdir build
    - cd build
    - cmake ../PROJET/
    - cmake --build .
  artifacts:
    paths:
      - build

test:
  stage: test
  image: ubuntu:latest
  script:
    - apt-get update -qq
    - apt-get install -y qtbase5-dev
    - GTEST_COLOR=1 ctest --test-dir build --output-on-failure -j12
  dependencies:
    - build

