stages:
  - build
  - test
  - deploy

before_script:
  - apk update
  - apk upgrade
  - apk add --no-cache cmake build-base

build:
  stage: build
  image: alpine
  script:
    - mkdir build
    - cd build
    - cmake ../TP-Refacto/
    - cmake --build .
  artifacts:
    paths:
      - build

test:
  stage: test
  image: alpine
  script:
    - GTEST_COLOR=1 ctest --test-dir build --output-on-failure -j12
  dependencies:
    - build
