build:
  stage: build
  tags:
    - linux
  image: gcc:13.2.0
  before_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y cmake
    - apt-get install --only-upgrade libstdc++6
  script:
    - mkdir build
    - cd build
    - cmake ../TP-Refacto/
    - cmake --build .
  artifacts:
    paths:
      - build
test:
  stage: test
  script:
    - cd build
    - UnitTests/Unit-Tests
  dependencies:
    - build
